# This file was generated by GoReleaser. DO NOT EDIT.
cask "gridctl" do
  name "gridctl"
  desc "MCP orchestration tool - Containerlab for AI Agents"
  homepage "https://github.com/gridctl/gridctl"
  version "0.0.0-sandbox-34309007058-1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gridctl"

  on_macos do
    on_intel do
      url "https://github.com/gridctl/release-verification-sandbox/releases/download/v#{version}/gridctl_#{version}_darwin_amd64.tar.gz"
      sha256 "339f8af42ebaa48ab404081ee442bf07db5aee71cd8748fc24b70b28854cf57a"
    end
    on_arm do
      url "https://github.com/gridctl/release-verification-sandbox/releases/download/v#{version}/gridctl_#{version}_darwin_arm64.tar.gz"
      sha256 "6bb3886c130eff638dbba3ed287376ad9686dded6272fcc805bc24533f5606b1"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gridctl/release-verification-sandbox/releases/download/v#{version}/gridctl_#{version}_linux_amd64.tar.gz"
      sha256 "b3c57ead6e1d951dff28ca3396285c90e22d042380a272f3c5bbccac5ea21a8f"
    end
    on_arm do
      url "https://github.com/gridctl/release-verification-sandbox/releases/download/v#{version}/gridctl_#{version}_linux_arm64.tar.gz"
      sha256 "0d0606985dbd3c7d2d3dcf5d69c51a712b3494681d5bfcb8cf31a1c82d44ec43"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gridctl"]
  end

  # No zap stanza required
end
