# This file was generated by GoReleaser. DO NOT EDIT.
cask "gridctl" do
  name "gridctl"
  desc "MCP orchestration tool - Containerlab for AI Agents"
  homepage "https://github.com/gridctl/gridctl"
  version "0.0.0-sandbox-34302490345-1"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gridctl"

  on_macos do
    on_intel do
      url "https://github.com/gridctl/release-verification-sandbox/releases/download/v#{version}/gridctl_#{version}_darwin_amd64.tar.gz"
      sha256 "a21c3065e35d3a9779e38c3020016a360c0da67c29a3fdbe1093cad3dffd7c80"
    end
    on_arm do
      url "https://github.com/gridctl/release-verification-sandbox/releases/download/v#{version}/gridctl_#{version}_darwin_arm64.tar.gz"
      sha256 "78eee4db9647af1f6eff8b7a38c26bfed2cb34d165f4d9b820481fc1a086cc65"
    end
  end

  on_linux do
    on_intel do
      url "https://github.com/gridctl/release-verification-sandbox/releases/download/v#{version}/gridctl_#{version}_linux_amd64.tar.gz"
      sha256 "0b8161cdbbf10f241d98cefa763ea63dba82fba62e3b83ccbc671ea61c1dce8e"
    end
    on_arm do
      url "https://github.com/gridctl/release-verification-sandbox/releases/download/v#{version}/gridctl_#{version}_linux_arm64.tar.gz"
      sha256 "0780762185c9b47f8cca550df6963190af3c817f91215ad2137c45d6e1b94c89"
    end
  end

  postflight do
    system_command "/usr/bin/xattr",
                   args: ["-dr", "com.apple.quarantine", "#{staged_path}/gridctl"]
  end

  # No zap stanza required
end
